baseURL = 'https://essencepartagee.github.io/'
languageCode = 'en-us'
title = 'Theoretical Explorations'
theme = 'PaperMod'

[params]
  description = 'Mathematical frameworks for understanding reality'
  author = 'Chris. M'
  
  # Enable math
  math = true

[markup.goldmark.renderer]
  unsafe = true